name: Performance Test

on:
  workflow_dispatch: {}   # manual trigger only

jobs:
  run-jmeter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter

      - name: Run JMeter tests
        run: |
          if [ ! -f perf-testing-petstore.jmx ]; then
            echo "❌ ERROR: Test plan perf-testing-petstore.jmx not found in repo root"
            exit 1
          fi
          mkdir -p results
          jmeter -n -t perf-testing-petstore.jmx -l results/results.jtl -e -o results/html || {
            echo "❌ JMeter execution failed"
            exit 1
          }
          echo "✅ JMeter test completed, results generated"


      - name: Debug results folder
        run: |
          echo "==== Results Folder Structure ===="
          ls -R results || echo "No results folder found"
          echo "================================="

      - name: Upload Results (HTML + JTL)
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: |
            results/results.jtl
            results/html
